//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_TTCMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_color
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_color()
        {
            this.tbl_productColor = new HashSet<tbl_productColor>();
        }
    
        public int color_id { get; set; }
        public string color_name { get; set; }
        public string color_img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_productColor> tbl_productColor { get; set; }
    }
}
