//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_TTCMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_product()
        {
            this.tbl_productColor = new HashSet<tbl_productColor>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_alias { get; set; }
        public string product_description { get; set; }
        public string product_content { get; set; }
        public string product_img { get; set; }
        public string product_sub_img { get; set; }
        public Nullable<bool> product_isHot { get; set; }
        public Nullable<bool> product_isNew { get; set; }
        public Nullable<bool> product_isSale { get; set; }
        public Nullable<System.DateTime> product_CreatedAt { get; set; }
        public Nullable<System.DateTime> product_UpdatedAt { get; set; }
        public string product_code { get; set; }
        public string product_package { get; set; }
        public string product_delivery { get; set; }
        public Nullable<System.DateTime> product_delivery_time { get; set; }
        public string product_payment { get; set; }
        public string product_payment_type { get; set; }
        public string product_sub_info { get; set; }
        public Nullable<int> state { get; set; }
        public string title_seo { get; set; }
        public string des_seo { get; set; }
        public string friendly_url { get; set; }
        public string keyword { get; set; }
        public string product_material { get; set; }
        public string product_shape { get; set; }
        public Nullable<int> product_producer { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> TongSoSao { get; set; }
        public Nullable<int> TongSoDanhGia { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_producer tbl_producer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_productColor> tbl_productColor { get; set; }
        public virtual tbl_state tbl_state { get; set; }
    }
}
