//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_TTCMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_admin
    {
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_password { get; set; }
        public string admin_phone { get; set; }
        public string admin_email { get; set; }
        public bool admin_isEmployee { get; set; }
    }
}
