//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_TTCMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orderDetail
    {
        public int order_detail_id { get; set; }
        public Nullable<int> productColor_id { get; set; }
        public Nullable<int> oder_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public string order_detail_note { get; set; }
    
        public virtual tbl_Order tbl_Order { get; set; }
        public virtual tbl_productColor tbl_productColor { get; set; }
    }
}
