//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_TTCMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cart()
        {
            this.tbl_cartDetail = new HashSet<tbl_cartDetail>();
        }
    
        public int cart_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<double> total_price { get; set; }
        public Nullable<System.DateTime> date_cart { get; set; }
        public Nullable<int> orderState_id { get; set; }
        public string note_buyer { get; set; }
        public System.Guid session_id { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cartDetail> tbl_cartDetail { get; set; }
    }
}
