#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_TTCMWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HAWContext")]
	public partial class DemoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_color(tbl_color instance);
    partial void Updatetbl_color(tbl_color instance);
    partial void Deletetbl_color(tbl_color instance);
    partial void Inserttbl_state(tbl_state instance);
    partial void Updatetbl_state(tbl_state instance);
    partial void Deletetbl_state(tbl_state instance);
    partial void Inserttbl_category(tbl_category instance);
    partial void Updatetbl_category(tbl_category instance);
    partial void Deletetbl_category(tbl_category instance);
    partial void Inserttbl_producer(tbl_producer instance);
    partial void Updatetbl_producer(tbl_producer instance);
    partial void Deletetbl_producer(tbl_producer instance);
    partial void Inserttbl_question(tbl_question instance);
    partial void Updatetbl_question(tbl_question instance);
    partial void Deletetbl_question(tbl_question instance);
    #endregion
		
		public DemoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HAWContextConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_color> tbl_colors
		{
			get
			{
				return this.GetTable<tbl_color>();
			}
		}
		
		public System.Data.Linq.Table<tbl_state> tbl_states
		{
			get
			{
				return this.GetTable<tbl_state>();
			}
		}
		
		public System.Data.Linq.Table<tbl_category> tbl_categories
		{
			get
			{
				return this.GetTable<tbl_category>();
			}
		}
		
		public System.Data.Linq.Table<Demo> Demos
		{
			get
			{
				return this.GetTable<Demo>();
			}
		}
		
		public System.Data.Linq.Table<Demo1> Demo1s
		{
			get
			{
				return this.GetTable<Demo1>();
			}
		}
		
		public System.Data.Linq.Table<Demo3> Demo3s
		{
			get
			{
				return this.GetTable<Demo3>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producer> tbl_producers
		{
			get
			{
				return this.GetTable<tbl_producer>();
			}
		}
		
		public System.Data.Linq.Table<order1> order1s
		{
			get
			{
				return this.GetTable<order1>();
			}
		}
		
		public System.Data.Linq.Table<product> products
		{
			get
			{
				return this.GetTable<product>();
			}
		}
		
		public System.Data.Linq.Table<producer> producers
		{
			get
			{
				return this.GetTable<producer>();
			}
		}
		
		public System.Data.Linq.Table<Demo2> Demo2s
		{
			get
			{
				return this.GetTable<Demo2>();
			}
		}
		
		public System.Data.Linq.Table<tbl_question> tbl_questions
		{
			get
			{
				return this.GetTable<tbl_question>();
			}
		}
		
		public System.Data.Linq.Table<Demo4> Demo4s
		{
			get
			{
				return this.GetTable<Demo4>();
			}
		}
		
		public System.Data.Linq.Table<TopSPbanchay> TopSPbanchays
		{
			get
			{
				return this.GetTable<TopSPbanchay>();
			}
		}
		
		public System.Data.Linq.Table<BanTheoNam> BanTheoNams
		{
			get
			{
				return this.GetTable<BanTheoNam>();
			}
		}
		
		public System.Data.Linq.Table<chitietOrder> chitietOrders
		{
			get
			{
				return this.GetTable<chitietOrder>();
			}
		}
		
		public System.Data.Linq.Table<productcolor> productcolors
		{
			get
			{
				return this.GetTable<productcolor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_color")]
	public partial class tbl_color : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _color_id;
		
		private string _color_name;
		
		private string _color_img;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncolor_idChanging(int value);
    partial void Oncolor_idChanged();
    partial void Oncolor_nameChanging(string value);
    partial void Oncolor_nameChanged();
    partial void Oncolor_imgChanging(string value);
    partial void Oncolor_imgChanged();
    #endregion
		
		public tbl_color()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int color_id
		{
			get
			{
				return this._color_id;
			}
			set
			{
				if ((this._color_id != value))
				{
					this.Oncolor_idChanging(value);
					this.SendPropertyChanging();
					this._color_id = value;
					this.SendPropertyChanged("color_id");
					this.Oncolor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_name", DbType="NVarChar(255)")]
		public string color_name
		{
			get
			{
				return this._color_name;
			}
			set
			{
				if ((this._color_name != value))
				{
					this.Oncolor_nameChanging(value);
					this.SendPropertyChanging();
					this._color_name = value;
					this.SendPropertyChanged("color_name");
					this.Oncolor_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_img", DbType="NVarChar(255)")]
		public string color_img
		{
			get
			{
				return this._color_img;
			}
			set
			{
				if ((this._color_img != value))
				{
					this.Oncolor_imgChanging(value);
					this.SendPropertyChanging();
					this._color_img = value;
					this.SendPropertyChanged("color_img");
					this.Oncolor_imgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_state")]
	public partial class tbl_state : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _state_id;
		
		private string _state_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstate_idChanging(int value);
    partial void Onstate_idChanged();
    partial void Onstate_nameChanging(string value);
    partial void Onstate_nameChanged();
    #endregion
		
		public tbl_state()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int state_id
		{
			get
			{
				return this._state_id;
			}
			set
			{
				if ((this._state_id != value))
				{
					this.Onstate_idChanging(value);
					this.SendPropertyChanging();
					this._state_id = value;
					this.SendPropertyChanged("state_id");
					this.Onstate_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(255)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this.Onstate_nameChanging(value);
					this.SendPropertyChanging();
					this._state_name = value;
					this.SendPropertyChanged("state_name");
					this.Onstate_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_category")]
	public partial class tbl_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _category_id;
		
		private string _category_name;
		
		private string _category_parent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncategory_idChanging(int value);
    partial void Oncategory_idChanged();
    partial void Oncategory_nameChanging(string value);
    partial void Oncategory_nameChanged();
    partial void Oncategory_parentChanging(string value);
    partial void Oncategory_parentChanged();
    #endregion
		
		public tbl_category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_name", DbType="NVarChar(255)")]
		public string category_name
		{
			get
			{
				return this._category_name;
			}
			set
			{
				if ((this._category_name != value))
				{
					this.Oncategory_nameChanging(value);
					this.SendPropertyChanging();
					this._category_name = value;
					this.SendPropertyChanged("category_name");
					this.Oncategory_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_parent", DbType="NVarChar(255)")]
		public string category_parent
		{
			get
			{
				return this._category_parent;
			}
			set
			{
				if ((this._category_parent != value))
				{
					this.Oncategory_parentChanging(value);
					this.SendPropertyChanging();
					this._category_parent = value;
					this.SendPropertyChanged("category_parent");
					this.Oncategory_parentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Demo")]
	public partial class Demo
	{
		
		private int _user_id;
		
		private string _user_name;
		
		private string _user_email;
		
		private string _user_phone;
		
		private string _user_address;
		
		private string _user_password;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
		private bool _isActive;
		
		private System.Nullable<System.DateTime> _time;
		
		private System.Nullable<int> _question_id;
		
		private string _answer;
		
		private string _remember_me_identify;
		
		private string _remember_me_token;
		
		private string _question;
		
		public Demo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(255)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="NVarChar(255)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this._user_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_phone", DbType="NVarChar(11)")]
		public string user_phone
		{
			get
			{
				return this._user_phone;
			}
			set
			{
				if ((this._user_phone != value))
				{
					this._user_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_address", DbType="NVarChar(500)")]
		public string user_address
		{
			get
			{
				return this._user_address;
			}
			set
			{
				if ((this._user_address != value))
				{
					this._user_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="NVarChar(255)")]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this._user_password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this._CreatedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit NOT NULL")]
		public bool isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this._isActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Date")]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", DbType="Int")]
		public System.Nullable<int> question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					this._question_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer", DbType="NVarChar(500)")]
		public string answer
		{
			get
			{
				return this._answer;
			}
			set
			{
				if ((this._answer != value))
				{
					this._answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remember_me_identify", DbType="NVarChar(500)")]
		public string remember_me_identify
		{
			get
			{
				return this._remember_me_identify;
			}
			set
			{
				if ((this._remember_me_identify != value))
				{
					this._remember_me_identify = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remember_me_token", DbType="NVarChar(255)")]
		public string remember_me_token
		{
			get
			{
				return this._remember_me_token;
			}
			set
			{
				if ((this._remember_me_token != value))
				{
					this._remember_me_token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question", DbType="NVarChar(500)")]
		public string question
		{
			get
			{
				return this._question;
			}
			set
			{
				if ((this._question != value))
				{
					this._question = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Demo1")]
	public partial class Demo1
	{
		
		private int _user_id;
		
		private string _user_name;
		
		private string _user_email;
		
		private string _user_phone;
		
		private string _user_address;
		
		private string _user_password;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
		private bool _isActive;
		
		private System.Nullable<System.DateTime> _time;
		
		private System.Nullable<int> _question_id;
		
		private string _answer;
		
		private string _remember_me_identify;
		
		private string _remember_me_token;
		
		private System.Nullable<int> _SoLanMua;
		
		public Demo1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(255)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="NVarChar(255)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this._user_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_phone", DbType="NVarChar(11)")]
		public string user_phone
		{
			get
			{
				return this._user_phone;
			}
			set
			{
				if ((this._user_phone != value))
				{
					this._user_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_address", DbType="NVarChar(500)")]
		public string user_address
		{
			get
			{
				return this._user_address;
			}
			set
			{
				if ((this._user_address != value))
				{
					this._user_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="NVarChar(255)")]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this._user_password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this._CreatedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit NOT NULL")]
		public bool isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this._isActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Date")]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", DbType="Int")]
		public System.Nullable<int> question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					this._question_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer", DbType="NVarChar(500)")]
		public string answer
		{
			get
			{
				return this._answer;
			}
			set
			{
				if ((this._answer != value))
				{
					this._answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remember_me_identify", DbType="NVarChar(500)")]
		public string remember_me_identify
		{
			get
			{
				return this._remember_me_identify;
			}
			set
			{
				if ((this._remember_me_identify != value))
				{
					this._remember_me_identify = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remember_me_token", DbType="NVarChar(255)")]
		public string remember_me_token
		{
			get
			{
				return this._remember_me_token;
			}
			set
			{
				if ((this._remember_me_token != value))
				{
					this._remember_me_token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanMua", DbType="Int")]
		public System.Nullable<int> SoLanMua
		{
			get
			{
				return this._SoLanMua;
			}
			set
			{
				if ((this._SoLanMua != value))
				{
					this._SoLanMua = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Demo3")]
	public partial class Demo3
	{
		
		private int _order_detail_id;
		
		private System.Nullable<int> _productColor_id;
		
		private System.Nullable<int> _oder_id;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<double> _price;
		
		private string _order_detail_note;
		
		private System.Nullable<int> _user_id;
		
		private string _product_name;
		
		private string _product_img;
		
		private System.Nullable<double> _TongTien;
		
		public Demo3()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_detail_id", DbType="Int NOT NULL")]
		public int order_detail_id
		{
			get
			{
				return this._order_detail_id;
			}
			set
			{
				if ((this._order_detail_id != value))
				{
					this._order_detail_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productColor_id", DbType="Int")]
		public System.Nullable<int> productColor_id
		{
			get
			{
				return this._productColor_id;
			}
			set
			{
				if ((this._productColor_id != value))
				{
					this._productColor_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oder_id", DbType="Int")]
		public System.Nullable<int> oder_id
		{
			get
			{
				return this._oder_id;
			}
			set
			{
				if ((this._oder_id != value))
				{
					this._oder_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this._quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_detail_note", DbType="NVarChar(255)")]
		public string order_detail_note
		{
			get
			{
				return this._order_detail_note;
			}
			set
			{
				if ((this._order_detail_note != value))
				{
					this._order_detail_note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(255)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this._product_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_img", DbType="NVarChar(255)")]
		public string product_img
		{
			get
			{
				return this._product_img;
			}
			set
			{
				if ((this._product_img != value))
				{
					this._product_img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this._TongTien = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producer")]
	public partial class tbl_producer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _producer_id;
		
		private string _producer_name;
		
		private string _producer_address;
		
		private System.Nullable<int> _state;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproducer_idChanging(int value);
    partial void Onproducer_idChanged();
    partial void Onproducer_nameChanging(string value);
    partial void Onproducer_nameChanged();
    partial void Onproducer_addressChanging(string value);
    partial void Onproducer_addressChanged();
    partial void OnstateChanging(System.Nullable<int> value);
    partial void OnstateChanged();
    #endregion
		
		public tbl_producer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int producer_id
		{
			get
			{
				return this._producer_id;
			}
			set
			{
				if ((this._producer_id != value))
				{
					this.Onproducer_idChanging(value);
					this.SendPropertyChanging();
					this._producer_id = value;
					this.SendPropertyChanged("producer_id");
					this.Onproducer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_name", DbType="NVarChar(255)")]
		public string producer_name
		{
			get
			{
				return this._producer_name;
			}
			set
			{
				if ((this._producer_name != value))
				{
					this.Onproducer_nameChanging(value);
					this.SendPropertyChanging();
					this._producer_name = value;
					this.SendPropertyChanged("producer_name");
					this.Onproducer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_address", DbType="NVarChar(255)")]
		public string producer_address
		{
			get
			{
				return this._producer_address;
			}
			set
			{
				if ((this._producer_address != value))
				{
					this.Onproducer_addressChanging(value);
					this.SendPropertyChanging();
					this._producer_address = value;
					this.SendPropertyChanged("producer_address");
					this.Onproducer_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order1")]
	public partial class order1
	{
		
		private int _order_id;
		
		private int _user_id;
		
		private string _user_name;
		
		private string _order_receiver_note;
		
		private System.Nullable<double> _order_total_price;
		
		private int _state_id;
		
		private string _state_name;
		
		public order1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL")]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this._order_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(255)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_receiver_note", DbType="NVarChar(255)")]
		public string order_receiver_note
		{
			get
			{
				return this._order_receiver_note;
			}
			set
			{
				if ((this._order_receiver_note != value))
				{
					this._order_receiver_note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_total_price", DbType="Float")]
		public System.Nullable<double> order_total_price
		{
			get
			{
				return this._order_total_price;
			}
			set
			{
				if ((this._order_total_price != value))
				{
					this._order_total_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", DbType="Int NOT NULL")]
		public int state_id
		{
			get
			{
				return this._state_id;
			}
			set
			{
				if ((this._state_id != value))
				{
					this._state_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(255)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this._state_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product")]
	public partial class product
	{
		
		private int _product_id;
		
		private string _product_name;
		
		private string _product_alias;
		
		private string _product_description;
		
		private string _product_content;
		
		private string _product_img;
		
		private string _product_sub_img;
		
		private System.Nullable<bool> _product_isHot;
		
		private System.Nullable<bool> _product_isNew;
		
		private System.Nullable<bool> _product_isSale;
		
		private System.Nullable<System.DateTime> _product_CreatedAt;
		
		private System.Nullable<System.DateTime> _product_UpdatedAt;
		
		private string _product_code;
		
		private string _product_package;
		
		private string _product_delivery;
		
		private System.Nullable<System.DateTime> _product_delivery_time;
		
		private string _product_payment;
		
		private string _product_payment_type;
		
		private System.Nullable<int> _state;
		
		private string _state_name;
		
		private string _title_seo;
		
		private string _des_seo;
		
		private string _friendly_url;
		
		private string _keyword;
		
		private string _product_material;
		
		private string _product_shape;
		
		private System.Nullable<int> _product_producer;
		
		private string _producer_name;
		
		private int _category_id;
		
		private string _category_name;
		
		public product()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL")]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this._product_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(255)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this._product_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_alias", DbType="NVarChar(255)")]
		public string product_alias
		{
			get
			{
				return this._product_alias;
			}
			set
			{
				if ((this._product_alias != value))
				{
					this._product_alias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_description", DbType="NVarChar(255)")]
		public string product_description
		{
			get
			{
				return this._product_description;
			}
			set
			{
				if ((this._product_description != value))
				{
					this._product_description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_content", DbType="NVarChar(255)")]
		public string product_content
		{
			get
			{
				return this._product_content;
			}
			set
			{
				if ((this._product_content != value))
				{
					this._product_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_img", DbType="NVarChar(255)")]
		public string product_img
		{
			get
			{
				return this._product_img;
			}
			set
			{
				if ((this._product_img != value))
				{
					this._product_img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sub_img", DbType="NVarChar(255)")]
		public string product_sub_img
		{
			get
			{
				return this._product_sub_img;
			}
			set
			{
				if ((this._product_sub_img != value))
				{
					this._product_sub_img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_isHot", DbType="Bit")]
		public System.Nullable<bool> product_isHot
		{
			get
			{
				return this._product_isHot;
			}
			set
			{
				if ((this._product_isHot != value))
				{
					this._product_isHot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_isNew", DbType="Bit")]
		public System.Nullable<bool> product_isNew
		{
			get
			{
				return this._product_isNew;
			}
			set
			{
				if ((this._product_isNew != value))
				{
					this._product_isNew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_isSale", DbType="Bit")]
		public System.Nullable<bool> product_isSale
		{
			get
			{
				return this._product_isSale;
			}
			set
			{
				if ((this._product_isSale != value))
				{
					this._product_isSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> product_CreatedAt
		{
			get
			{
				return this._product_CreatedAt;
			}
			set
			{
				if ((this._product_CreatedAt != value))
				{
					this._product_CreatedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_UpdatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> product_UpdatedAt
		{
			get
			{
				return this._product_UpdatedAt;
			}
			set
			{
				if ((this._product_UpdatedAt != value))
				{
					this._product_UpdatedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_code", DbType="NVarChar(255)")]
		public string product_code
		{
			get
			{
				return this._product_code;
			}
			set
			{
				if ((this._product_code != value))
				{
					this._product_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_package", DbType="NVarChar(255)")]
		public string product_package
		{
			get
			{
				return this._product_package;
			}
			set
			{
				if ((this._product_package != value))
				{
					this._product_package = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_delivery", DbType="NVarChar(255)")]
		public string product_delivery
		{
			get
			{
				return this._product_delivery;
			}
			set
			{
				if ((this._product_delivery != value))
				{
					this._product_delivery = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_delivery_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> product_delivery_time
		{
			get
			{
				return this._product_delivery_time;
			}
			set
			{
				if ((this._product_delivery_time != value))
				{
					this._product_delivery_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_payment", DbType="NVarChar(255)")]
		public string product_payment
		{
			get
			{
				return this._product_payment;
			}
			set
			{
				if ((this._product_payment != value))
				{
					this._product_payment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_payment_type", DbType="NVarChar(255)")]
		public string product_payment_type
		{
			get
			{
				return this._product_payment_type;
			}
			set
			{
				if ((this._product_payment_type != value))
				{
					this._product_payment_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(255)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this._state_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title_seo", DbType="NVarChar(255)")]
		public string title_seo
		{
			get
			{
				return this._title_seo;
			}
			set
			{
				if ((this._title_seo != value))
				{
					this._title_seo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_seo", DbType="NVarChar(255)")]
		public string des_seo
		{
			get
			{
				return this._des_seo;
			}
			set
			{
				if ((this._des_seo != value))
				{
					this._des_seo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friendly_url", DbType="NVarChar(255)")]
		public string friendly_url
		{
			get
			{
				return this._friendly_url;
			}
			set
			{
				if ((this._friendly_url != value))
				{
					this._friendly_url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyword", DbType="NVarChar(255)")]
		public string keyword
		{
			get
			{
				return this._keyword;
			}
			set
			{
				if ((this._keyword != value))
				{
					this._keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_material", DbType="NVarChar(255)")]
		public string product_material
		{
			get
			{
				return this._product_material;
			}
			set
			{
				if ((this._product_material != value))
				{
					this._product_material = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_shape", DbType="NVarChar(255)")]
		public string product_shape
		{
			get
			{
				return this._product_shape;
			}
			set
			{
				if ((this._product_shape != value))
				{
					this._product_shape = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_producer", DbType="Int")]
		public System.Nullable<int> product_producer
		{
			get
			{
				return this._product_producer;
			}
			set
			{
				if ((this._product_producer != value))
				{
					this._product_producer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_name", DbType="NVarChar(255)")]
		public string producer_name
		{
			get
			{
				return this._producer_name;
			}
			set
			{
				if ((this._producer_name != value))
				{
					this._producer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int NOT NULL")]
		public int category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this._category_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_name", DbType="NVarChar(255)")]
		public string category_name
		{
			get
			{
				return this._category_name;
			}
			set
			{
				if ((this._category_name != value))
				{
					this._category_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producer")]
	public partial class producer
	{
		
		private int _producer_id;
		
		private string _producer_name;
		
		private string _producer_address;
		
		private System.Nullable<int> _state;
		
		private string _state_name;
		
		public producer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_id", DbType="Int NOT NULL")]
		public int producer_id
		{
			get
			{
				return this._producer_id;
			}
			set
			{
				if ((this._producer_id != value))
				{
					this._producer_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_name", DbType="NVarChar(255)")]
		public string producer_name
		{
			get
			{
				return this._producer_name;
			}
			set
			{
				if ((this._producer_name != value))
				{
					this._producer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_address", DbType="NVarChar(255)")]
		public string producer_address
		{
			get
			{
				return this._producer_address;
			}
			set
			{
				if ((this._producer_address != value))
				{
					this._producer_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(255)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this._state_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Demo2")]
	public partial class Demo2
	{
		
		private System.Nullable<int> _order_id;
		
		private System.Nullable<int> _user_id;
		
		private string _order_receiver_note;
		
		private System.Nullable<double> _order_total_price;
		
		private System.Nullable<int> _order_state;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _user_name;
		
		private string _state_name;
		
		public Demo2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int")]
		public System.Nullable<int> order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this._order_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_receiver_note", DbType="NVarChar(255)")]
		public string order_receiver_note
		{
			get
			{
				return this._order_receiver_note;
			}
			set
			{
				if ((this._order_receiver_note != value))
				{
					this._order_receiver_note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_total_price", DbType="Float")]
		public System.Nullable<double> order_total_price
		{
			get
			{
				return this._order_total_price;
			}
			set
			{
				if ((this._order_total_price != value))
				{
					this._order_total_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_state", DbType="Int")]
		public System.Nullable<int> order_state
		{
			get
			{
				return this._order_state;
			}
			set
			{
				if ((this._order_state != value))
				{
					this._order_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(255)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(255)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this._state_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_question")]
	public partial class tbl_question : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _question_id;
		
		private string _question;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onquestion_idChanging(int value);
    partial void Onquestion_idChanged();
    partial void OnquestionChanging(string value);
    partial void OnquestionChanged();
    #endregion
		
		public tbl_question()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					this.Onquestion_idChanging(value);
					this.SendPropertyChanging();
					this._question_id = value;
					this.SendPropertyChanged("question_id");
					this.Onquestion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question", DbType="NVarChar(500)")]
		public string question
		{
			get
			{
				return this._question;
			}
			set
			{
				if ((this._question != value))
				{
					this.OnquestionChanging(value);
					this.SendPropertyChanging();
					this._question = value;
					this.SendPropertyChanged("question");
					this.OnquestionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Demo4")]
	public partial class Demo4
	{
		
		private int _user_id;
		
		private string _user_name;
		
		public Demo4()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(255)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TopSPbanchay")]
	public partial class TopSPbanchay
	{
		
		private System.Nullable<int> _Nam;
		
		private System.Nullable<int> _Thang;
		
		private System.Nullable<int> _SoSP;
		
		private System.Nullable<double> _TongTien;
		
		private string _product_name;
		
		private string _size;
		
		private string _color_name;
		
		private string _product_img;
		
		public TopSPbanchay()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this._Thang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoSP", DbType="Int")]
		public System.Nullable<int> SoSP
		{
			get
			{
				return this._SoSP;
			}
			set
			{
				if ((this._SoSP != value))
				{
					this._SoSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this._TongTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(255)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this._product_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="NVarChar(255)")]
		public string size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this._size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_name", DbType="NVarChar(255)")]
		public string color_name
		{
			get
			{
				return this._color_name;
			}
			set
			{
				if ((this._color_name != value))
				{
					this._color_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_img", DbType="NVarChar(255)")]
		public string product_img
		{
			get
			{
				return this._product_img;
			}
			set
			{
				if ((this._product_img != value))
				{
					this._product_img = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BanTheoNam")]
	public partial class BanTheoNam
	{
		
		private System.Nullable<int> _Nam;
		
		private System.Nullable<int> _Thang;
		
		private System.Nullable<int> _TongHD;
		
		private System.Nullable<int> _SoSP;
		
		private System.Nullable<double> _TongTien;
		
		public BanTheoNam()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this._Thang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongHD", DbType="Int")]
		public System.Nullable<int> TongHD
		{
			get
			{
				return this._TongHD;
			}
			set
			{
				if ((this._TongHD != value))
				{
					this._TongHD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoSP", DbType="Int")]
		public System.Nullable<int> SoSP
		{
			get
			{
				return this._SoSP;
			}
			set
			{
				if ((this._SoSP != value))
				{
					this._SoSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this._TongTien = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietOrder")]
	public partial class chitietOrder
	{
		
		private int _order_id;
		
		private System.Nullable<int> _user_id;
		
		private string _order_receiver_note;
		
		private System.Nullable<double> _order_total_price;
		
		private System.Nullable<int> _order_state;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _color_name;
		
		private string _state_name;
		
		private string _product_name;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<double> _price;
		
		private string _size;
		
		private string _product_img;
		
		private int _id;
		
		public chitietOrder()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL")]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this._order_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_receiver_note", DbType="NVarChar(255)")]
		public string order_receiver_note
		{
			get
			{
				return this._order_receiver_note;
			}
			set
			{
				if ((this._order_receiver_note != value))
				{
					this._order_receiver_note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_total_price", DbType="Float")]
		public System.Nullable<double> order_total_price
		{
			get
			{
				return this._order_total_price;
			}
			set
			{
				if ((this._order_total_price != value))
				{
					this._order_total_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_state", DbType="Int")]
		public System.Nullable<int> order_state
		{
			get
			{
				return this._order_state;
			}
			set
			{
				if ((this._order_state != value))
				{
					this._order_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_name", DbType="NVarChar(255)")]
		public string color_name
		{
			get
			{
				return this._color_name;
			}
			set
			{
				if ((this._color_name != value))
				{
					this._color_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(255)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this._state_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(255)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this._product_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this._quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="NVarChar(255)")]
		public string size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this._size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_img", DbType="NVarChar(255)")]
		public string product_img
		{
			get
			{
				return this._product_img;
			}
			set
			{
				if ((this._product_img != value))
				{
					this._product_img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.productcolor")]
	public partial class productcolor
	{
		
		private int _id;
		
		private int _color_id;
		
		private string _color_name;
		
		private int _product_id;
		
		private string _product_name;
		
		private string _size;
		
		private int _amount;
		
		private System.Nullable<double> _product_price;
		
		private System.Nullable<double> _product_sale;
		
		private System.Nullable<double> _product_discount;
		
		public productcolor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_id", DbType="Int NOT NULL")]
		public int color_id
		{
			get
			{
				return this._color_id;
			}
			set
			{
				if ((this._color_id != value))
				{
					this._color_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_name", DbType="NVarChar(255)")]
		public string color_name
		{
			get
			{
				return this._color_name;
			}
			set
			{
				if ((this._color_name != value))
				{
					this._color_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL")]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this._product_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(255)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this._product_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="NVarChar(255)")]
		public string size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this._size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Int NOT NULL")]
		public int amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this._amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_price", DbType="Float")]
		public System.Nullable<double> product_price
		{
			get
			{
				return this._product_price;
			}
			set
			{
				if ((this._product_price != value))
				{
					this._product_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sale", DbType="Float")]
		public System.Nullable<double> product_sale
		{
			get
			{
				return this._product_sale;
			}
			set
			{
				if ((this._product_sale != value))
				{
					this._product_sale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_discount", DbType="Float")]
		public System.Nullable<double> product_discount
		{
			get
			{
				return this._product_discount;
			}
			set
			{
				if ((this._product_discount != value))
				{
					this._product_discount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
